services:

  mysql:
    image: mysql:8.0
    container_name: robostore-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: robostore
      MYSQL_USER: robouser
      MYSQL_PASSWORD: robopassword

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data: